import {readFile,writeFile} from 'node:fs/promises'
import {JSDOM} from 'jsdom'
const base='.evidence/review/ssr-a11y/'
const r=JSON.parse(await readFile(base+'browser.json','utf8')),s=JSON.parse(await readFile(base+'supplement.json','utf8'))
function canonical(markup){const d=new JSDOM('<div id="wrap">'+markup+'</div>').window.document;function walk(n){if(n.nodeType===3)return n.textContent.trim()?n.textContent:null;if(n.nodeType!==1)return null;let attrs={};for(const a of [...n.attributes].sort((a,b)=>a.name.localeCompare(b.name))){if(['id','aria-describedby','aria-activedescendant','clip-path','data-v-app'].includes(a.name))continue;if(a.name==='style'){const v=[...Array(n.style.length)].map((_,i)=>n.style[i]).sort().map(k=>[k,n.style.getPropertyValue(k).trim().replace(/currentColor/gi,'currentcolor').replace(/^0px$/, '0').replace(/url\(#[^)]+\)/g,'url(#ID)')]);if(v.length)attrs.style=v}else attrs[a.name]=a.value.replace(/url\(#[^)]+\)/g,'url(#ID)')}return{tag:n.tagName,attrs,children:[...n.childNodes].map(walk).filter(x=>x!==null)}}return walk(d.getElementById('wrap'))}
const output=s.map(x=>{const a=canonical(x.final.markup),b=canonical(x.baseline.markup);return {name:x.name,normalizedDOMMatches:JSON.stringify(a)===JSON.stringify(b),textMatches:x.textMatches,final:a,baseline:b}})
await writeFile(base+'dom-comparison.json',JSON.stringify(output,null,2))
console.log(output.map(x=>[x.name,x.normalizedDOMMatches,x.textMatches]));
function shapes(a){return a.map(x=>({...x,style:x.style?.replace(/\s+/g,'')||null}))}
const rows=r.filter(x=>x.mode==='fixed'&&x.theme==='light'&&!x.reduced).map(x=>({name:x.name,errors:x.errors.length,mismatches:x.warnings.filter(s=>s.includes('[Vue warn]: Hydration')).length,settledShapes:JSON.stringify(shapes(x.final.shape))===JSON.stringify(shapes(x.baseline.shape)),geometrySet:JSON.stringify(shapes(x.final.shape).map(JSON.stringify).sort())===JSON.stringify(shapes(x.baseline.shape).map(JSON.stringify).sort()),entrance:x.entrance,stable:x.stable,reduced:r.find(a=>a.name===x.name&&a.reduced)?.reducedAnimation,role:x.a11yBefore.roles.filter(x=>x.role!=='tooltip')[0],tooltip:x.keyboardRight?.tooltip?.some(x=>x.visibility==='visible'&&x.text),axeLight:x.axeAfter?.map(v=>[v.rule,v.impact,v.count]),axeDark:r.find(a=>a.name===x.name&&a.theme==='dark'&&a.mode==='fixed')?.axeAfter?.map(v=>[v.rule,v.impact,v.count])}))
console.log(rows);await writeFile(base+'summary.json',JSON.stringify({rows,dom:output.map(({final,baseline,...x})=>x)},null,2))
