import {createRequire} from 'node:module';import{realpath,readFile,writeFile}from'node:fs/promises';import{resolve}from'node:path'
const root=resolve('.evidence/review/ssr-a11y'),r=createRequire(await realpath('packages/vue/node_modules/@nuxt/test-utils/package.json'));const{chromium}=r('playwright-core');const b=await chromium.launch({executablePath:'<local headless shell>'});const names=Object.keys(JSON.parse(await readFile(root+'/ssr.json','utf8'))).filter(n=>n.endsWith('-fixed')).map(n=>n.slice(0,-6));const only=process.env.AUDIT_ONLY?.split(',');const results=only?JSON.parse(await readFile(root+'/supplement.json','utf8')).filter(x=>!only.includes(x.name)):[]
function semantic(id){const host=document.getElementById(id);const copy=host.cloneNode(true);for(const e of copy.querySelectorAll('*'))for(const a of [...e.attributes])if(a.name==='id'||a.name==='aria-describedby'||a.name==='aria-activedescendant'||a.name==='clip-path'||a.name==='data-v-app')e.removeAttribute(a.name);for(const e of copy.querySelectorAll('[style]'))e.setAttribute('style',e.getAttribute('style').replace(/url\(#[^)]+\)/g,'url(#ID)'));return {text:host.textContent,markup:copy.innerHTML}}
function cellContrast(){
 function lum(c){const a=c.match(/[\d.]+/g)?.slice(0,3).map(Number);if(!a)return null;return a.map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((s,v,i)=>s+v*[.2126,.7152,.0722][i],0)}
 const texts=[...document.querySelectorAll('#host .v-charts-cell text,#host .v-charts-treemap text,#host .v-charts-bar-list-name')];return texts.map(e=>{const s=getComputedStyle(e);const rect=e.closest('.v-charts-cell')?.querySelector('.v-charts-cell-rect')||e.parentElement.querySelector('rect')||e.closest('.v-charts-bar-list-row')?.querySelector('.v-charts-bar-list-bar');const fg=e.tagName==='text'?s.fill:s.color;const bg=rect?rect.tagName==='rect'?getComputedStyle(rect).fill:getComputedStyle(rect).backgroundColor:getComputedStyle(document.body).backgroundColor;const f=lum(fg),back=lum(bg);return {text:e.textContent,fg,bg,ratio:f===null||back===null?null:(Math.max(f,back)+.05)/(Math.min(f,back)+.05),rectOpacity:rect?getComputedStyle(rect).opacity:null}})
}
try{for(const name of names.filter(x=>!only||only.includes(x))){const page=await b.newPage({viewport:{width:900,height:650}});await page.addInitScript(()=>{window.__VUE_OPTIONS_API__=true;window.__VUE_PROD_DEVTOOLS__=false;window.__VUE_PROD_HYDRATION_MISMATCH_DETAILS__=true});const errors=[];page.on('pageerror',e=>errors.push(e.stack));await page.goto(`http://127.0.0.1:4607/audit?name=${name}&mode=fixed`);await page.waitForFunction(()=>window.ready);await page.evaluate(()=>window.hydrate());await page.waitForTimeout(1600);const final=await page.evaluate(semantic,'host');const cellsLight=await page.evaluate(cellContrast);await page.evaluate(()=>document.documentElement.classList.add('dark'));const cellsDark=await page.evaluate(cellContrast);await page.evaluate(()=>document.documentElement.classList.remove('dark'));
 const focus=[];const count=await page.locator('#host [tabindex="0"],#host a,#host button,#host input').count();for(let j=0;j<count;j++){await page.keyboard.press('Tab');const before=await page.evaluate(()=>{const e=document.activeElement;return{tag:e.tagName,role:e.getAttribute('role'),cls:e.getAttribute('class'),name:e.getAttribute('aria-label'),value:e.getAttribute('aria-valuenow'),html:e.outerHTML.slice(0,400),outline:getComputedStyle(e).outline}});await page.keyboard.press('ArrowRight');await page.waitForTimeout(180);const after=await page.evaluate(()=>{const e=document.activeElement;return{value:e.getAttribute('aria-valuenow'),text:document.getElementById('host').textContent,tooltip:[...document.querySelectorAll('#host [role="tooltip"]')].map(e=>({text:e.textContent,visibility:getComputedStyle(e).visibility})),selected:[...document.querySelectorAll('#host [aria-selected="true"]')].map(e=>e.getAttribute('aria-label'))}});let enter=null;if(before.role==='button'){await page.keyboard.press('Enter');await page.waitForTimeout(100);enter=await page.evaluate(()=>({text:document.getElementById('host').textContent,hidden:[...document.querySelectorAll('#host .v-charts-legend-item')].map(e=>e.outerHTML)}))}focus.push({before,after,enter})}
 await page.evaluate(()=>{window.app.unmount();document.getElementById('host').innerHTML='';window.baseline()});await page.waitForTimeout(150);const baseline=await page.evaluate(semantic,'baseline');results.push({name,textMatches:final.text===baseline.text,normalizedDOMMatches:final.markup===baseline.markup,final,baseline,cellsLight,cellsDark,focus,errors});await writeFile(root+'/supplement.json',JSON.stringify(results,null,2));console.log(name,'normalized DOM',final.markup===baseline.markup,'text',final.text===baseline.text,'focus targets',count);await page.close()}}finally{await b.close()}
