import antfu from '@antfu/eslint-config'

export default antfu(
  {
    vue: true,
    typescript: true,
    ignores: [
      '**/dist/**',
      '**/.nuxt/**',
      '**/.output/**',
      '**/.data/**',
      '**/coverage/**',
      'storybook-static/**',
      'packages/vue/src/__breakit__/**',
      'packages/vue/test/fixtures/lab/**',
      '.evidence/**',
      'internals/release-1.0/**',
      // Symlink to packages/vue/README.md; lint the file once, at its source.
      'README.md',
    ],
  },
  {
    ignores: ['*.js'],
  },
  {
    rules: {
      'ts/no-non-null-asserted-optional-chain': 'off',
      'ts/ban-ts-comment': 'warn',
      'ts/consistent-type-definitions': 'off',
      'ts/no-unsafe-function-type': 'off',
      'ts/no-unused-expressions': 'off',
      'ts/no-empty-object-type': 'off',
      'symbol-description': 'off',
      'no-console': 'warn',
      'import/first': 'off',
      'import/order': 'off',
      'style/max-statements-per-line': ['error', { max: 2 }],
      'vue/one-component-per-file': 'off',
      'unicorn/prefer-dom-node-text-content': 'off',
      'unicorn/prefer-number-properties': 'off',
      'unused-imports/no-unused-vars': 'off',
      'regexp/no-super-linear-backtracking': 'off',
      'vue/no-parsing-error': [2, { 'x-invalid-namespace': false }],
      'no-async-promise-executor': 'off',
      'node/prefer-global/process': 'off',
    },
  },
  {
    files: ['**/*.vue'],
    rules: {
      'vue/max-attributes-per-line': ['error', {
        singleline: 1,
        multiline: 1,
      }],
    },
  },
  {
    files: ['packages/vue/src/core/**/*.ts'],
    ignores: ['**/__tests__/**'],
    rules: {
      'no-restricted-imports': ['error', {
        paths: [{ name: '@/utils', message: 'Import a pure utility directly, not the browser utility barrel.' }],
        patterns: [{
          group: [
            'vue',
            'vue/*',
            '@vue/*',
            'motion-v',
            'motion-v/*',
            'motion-dom',
            '@/utils/DOMUtils',
            '@/utils/attrs',
            '@/utils/Global',
            '@/utils/VueUtils',
            '@/utils/chart',
            '**/utils/DOMUtils',
            '**/utils/attrs',
            '**/utils/Global',
            '**/utils/VueUtils',
            '**/utils/chart',
            '@/model/**',
            '@/state/**',
            '@/components/**',
            '@/chart/**',
            '@/cartesian/**',
            '@/polar/**',
            '@/container/**',
            '@/shape/**',
            '**/model/**',
            '**/state/**',
            '**/components/**',
            '**/chart/**',
            '**/cartesian/**',
            '**/polar/**',
            '**/container/**',
            '**/shape/**',
          ],
          message: 'Core math must depend only on pure functions and domain types.',
        }],
      }],
      'no-restricted-globals': [
        'error',
        'window',
        'document',
        'navigator',
        'localStorage',
        'sessionStorage',
        'IntersectionObserver',
        'ResizeObserver',
        'MutationObserver',
        'requestAnimationFrame',
        'cancelAnimationFrame',
        'getComputedStyle',
        'matchMedia',
        'customElements',
        'fetch',
      ],
    },
  },
  {
    files: ['packages/vue/src/**/*.{ts,tsx,vue}'],
    ignores: [
      '**/__tests__/**',
      '**/__stories__/**',
      '**/storybook/**',
      '**/test/**',
      '**/__breakit__/**',
      '**/*.stories.*',
      '**/*.story.*',
    ],
    rules: { 'ts/no-explicit-any': 'error' },
  },
)
