import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import {createRequire} from 'node:module';import {execFileSync} from 'node:child_process';
const require=createRequire(import.meta.url),dir=path.resolve('.evidence/review/performance');
const {build}=require(path.resolve('node_modules/.pnpm/esbuild@0.28.2/node_modules/esbuild'));
const {chromium}=require(path.resolve('node_modules/.pnpm/playwright-core@1.58.2/node_modules/playwright-core'));
await build({entryPoints:[path.join(dir,'runtime-fixture.mjs')],nodePaths:[path.resolve('packages/vue/node_modules')],bundle:true,minify:true,format:'iife',platform:'browser',target:'es2022',outfile:path.join(dir,'animated.js'),alias:{vue:require.resolve('vue',{paths:[path.resolve('packages/vue')]}).replace('/index.js','/dist/vue.runtime.esm-bundler.js'),'motion-v':path.resolve('packages/vue/node_modules/motion-v/dist/es/index.mjs')},define:{'process.env.NODE_ENV':'"production"',__VUE_OPTIONS_API__:'true',__VUE_PROD_DEVTOOLS__:'false',__VUE_PROD_HYDRATION_MISMATCH_DETAILS__:'false'}});
const server=http.createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/animated.js'?'text/javascript':'text/html');res.end(req.url==='/animated.js'?fs.readFileSync(path.join(dir,'animated.js')):'<div id="app"></div><script src="/animated.js"></script>');});
let browser;const result={uptimeStart:execFileSync('uptime').toString().trim(),runs:[],errors:[]};
try{await new Promise((r,j)=>{server.once('error',j);server.listen(4601,'127.0.0.1',r);});browser=await chromium.launch({headless:true,executablePath:'<local headless shell>'});const page=await browser.newPage({viewport:{width:1100,height:700}});page.on('pageerror',e=>result.errors.push(String(e)));await page.goto('http://127.0.0.1:4601');await page.waitForFunction(()=>!!window.bench);const cdp=await page.context().newCDPSession(page);await cdp.send('Performance.enable');const metrics=async()=>Object.fromEntries((await cdp.send('Performance.getMetrics')).metrics.map(m=>[m.name,m.value]));
for(const kind of ['LineChart','BarChart'])for(const n of [100,1000,10000]){await page.evaluate(([k,n])=>window.bench.prepareAnimated(k,n),[kind,n]);for(let run=0;run<5;run++){const before=await metrics();const row=await page.evaluate(([k,n,p])=>window.bench.animatedUpdate(k,n,p),[kind,n,run+1]);const after=await metrics();const cpuMs=(after.TaskDuration-before.TaskDuration)*1000;const x={kind,n,run,...row,cpuMs,cpuMsPerFrame:cpuMs/row.frames,scriptMs:(after.ScriptDuration-before.ScriptDuration)*1000,layoutMs:(after.LayoutDuration-before.LayoutDuration)*1000};result.runs.push(x);console.log(JSON.stringify(x));fs.writeFileSync(path.join(dir,'animated-results.json'),JSON.stringify(result,null,2));}await page.evaluate(()=>window.bench.endAnimated());}
result.uptimeEnd=execFileSync('uptime').toString().trim();fs.writeFileSync(path.join(dir,'animated-results.json'),JSON.stringify(result,null,2));}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}
